ALTER TABLE games ADD COLUMN IF NOT EXISTS rating_applied BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ALTER COLUMN elo SET DEFAULT 1000;
ALTER TABLE users ALTER COLUMN peak_elo SET DEFAULT 1000;
